### PR TITLE
Add bot announce

### LINKED ISSUE #10: Have bot announce its presence when connected
This is something that I'm currently doing so that I can see when the bot connects, since there's no visible indicator in VictorOps that there's a bot connected using the Hubot integration, and with each update to VictorOps on the backend disconnecting Hubot, this can be used to confirm that the bot started back up successfully after the update.

I'm currently doing this inside the `receiveWS` method, in this block:

``` coffeescript
    else if data.MESSAGE == "LOGIN_REPLY_MESSAGE"
      if data.PAYLOAD.STATUS != "200"
        @robot.logger.info "Failed to log in: #{data.PAYLOAD.DESCRIPTION}"
        @loggedIn = false
        @ws.terminate()
      else
        @loginAttempts = @getLoginAttempts()
        @loggedIn = true
        @sendToVO(@chat(@robot.name + " reporting for duty!"))
        setTimeout =>
          if ( ! @rcvdStatusList )
            @robot.logger.info "Did not get status list in time; reconnecting..."
            @disconnect()
        , 5000
```

Specifically the `@sendToVO(@chat(@robot.name + " reporting for duty!"))` line. This just produces a simple line in the Timeline, so I know that my bot has successfully connected:

image

Think this would be useful in an overall sense, or is it something that folks would get annoyed with?

### PR DESCRIPTION
**Pull request by jm-welch**
Fixes #10

### CODE REVIEW

**Comment by jm-welch** [comment]
Bot will announce its presence if `HUBOT_ANNOUNCE` environment variable is set, but take no additional action if it is not set.

**Comment by charlie-vo** [comment]
Will you please bump the version as well?

**Comment by jm-welch** [comment]
Version done bumped and readme updated to include the new env var.

**Comment by charlie-vo** [comment]
Actually, the version should be .13 (or .14 if you're superstitious).

**Comment by jm-welch** [comment]
Not sure what conflict this is reporting now.

**Comment by jm-welch** [comment]
Closing this - will resubmit this and a fix for #14 as one pull request, without the conflict.

**Pull request closed without merging**
