### PR TITLE
Bot-announce and new redis storage mechanism

### PR DESCRIPTION
**Pull request by jm-welch**
Addresses #10, #13, #14

### CODE REVIEW

**Comment by jm-welch** [comment]
Tested this, and both changes are working.

### Important
This will break any custom scripts that rely on either the `_private.VO_INCIDENT_KEYS` list or accessing incident alert data via a simple `@robot.brain.get <incNum>`.

To update scripts of the latter category, use this instead (replacing `1091` with the actual number in question, though it should be a string):

``` coffeescript
@robot.brain.get("VO_INCIDENTS")['1091']
```

**Comment by charlie-vo** [comment]
Trying to get an idea from our customers who would be affected by the breaking change.

**Comment by jm-welch** [comment]
Want me to resubmit this against the dev branch?

**Comment by charlie-vo** [comment]
Sure, sounds good

**Comment by jm-welch** [comment]
Closing to resubmit against dev.

**Pull request closed without merging**
